import { SkillFile } from "../utils/skills";

export function renderAgentsMarkdown(skills: SkillFile[]): string {
  const alwaysApply = skills.filter((skill) => skill.frontmatter.alwaysApply);

  if (alwaysApply.length === 0) {
    return "No always-apply skills are currently configured.";
  }

  const blocks = alwaysApply.map((skill) => skill.body.trim());

  return [
    "# Cicada Agents",
    "",
    "This file is generated by cicada compile.",
    "",
    ...blocks.join("\n\n---\n\n").split("\n")
  ].join("\n");
}
