import fs from "fs-extra";
import path from "path";
import yaml from "yaml";

export interface SkillFrontmatter {
  name: string;
  description?: string;
  globs?: string[];
  alwaysApply?: boolean;
}

export interface SkillFile {
  id: string;
  dirPath: string;
  skillPath: string;
  frontmatter: SkillFrontmatter;
  body: string;
  raw: string;
}

export interface SkillIndexEntry {
  id: string;
  name: string;
  description: string;
  globs: string[];
  alwaysApply: boolean;
}

export async function listSkillDirectories(skillsDir: string): Promise<string[]> {
  if (!(await fs.pathExists(skillsDir))) {
    return [];
  }

  const entries = await fs.readdir(skillsDir, { withFileTypes: true });
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
}

export async function loadSkills(skillsDir: string): Promise<SkillFile[]> {
  const skillDirs = await listSkillDirectories(skillsDir);
  const skills: SkillFile[] = [];

  for (const dirName of skillDirs) {
    const skillPath = path.join(skillsDir, dirName, "SKILL.md");
    if (!(await fs.pathExists(skillPath))) {
      continue;
    }

    skills.push(await readSkillFile(dirName, skillPath));
  }

  return skills.sort((a, b) => a.frontmatter.name.localeCompare(b.frontmatter.name));
}

export async function readSkillFile(id: string, skillPath: string): Promise<SkillFile> {
  const raw = await fs.readFile(skillPath, "utf8");
  const { frontmatter, body } = parseSkillContent(raw, id);

  return {
    id,
    dirPath: path.dirname(skillPath),
    skillPath,
    frontmatter,
    body,
    raw
  };
}

export function parseSkillContent(content: string, id: string): { frontmatter: SkillFrontmatter; body: string } {
  const lines = content.split(/\r?\n/);
  if (lines.length === 0 || lines[0].trim() !== "---") {
    throw new Error(`Skill ${id} is missing frontmatter`);
  }

  const endIndex = lines.slice(1).findIndex((line) => line.trim() === "---");
  if (endIndex === -1) {
    throw new Error(`Skill ${id} frontmatter is not closed`);
  }

  const frontmatterText = lines.slice(1, endIndex + 1).join("\n");
  const body = lines.slice(endIndex + 2).join("\n").trimStart();
  const data = yaml.parse(frontmatterText) as SkillFrontmatter;

  if (!data?.name) {
    throw new Error(`Skill ${id} is missing a name in frontmatter`);
  }

  const globs = normalizeGlobs(data.globs);

  return {
    frontmatter: {
      name: data.name,
      description: data.description ?? "",
      globs,
      alwaysApply: Boolean(data.alwaysApply)
    },
    body
  };
}

export function buildSkillIndex(skills: SkillFile[]): { markdown: string; json: string } {
  const entries = skills.map(toIndexEntry);

  const rows = entries.map((entry) => {
    const globs = entry.globs.length > 0 ? entry.globs.join(", ") : "-";
    const alwaysApply = entry.alwaysApply ? "yes" : "no";
    return `| ${entry.name} | ${entry.id} | ${entry.description || "-"} | ${globs} | ${alwaysApply} |`;
  });

  const markdown = [
    "# Cicada Skills Index",
    "",
    "This index is regenerated by Cicada on every compile.",
    "",
    "| Skill | Folder | Description | Globs | Always Apply |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    "## How to use this index",
    "1. Review the Description and Globs columns",
    "2. Load the relevant skill folders from .cicada/skills/",
    "3. Apply their rules for the current task",
    ""
  ].join("\n");

  const json = JSON.stringify({ skills: entries }, null, 2);

  return { markdown, json };
}

function toIndexEntry(skill: SkillFile): SkillIndexEntry {
  const globs = normalizeGlobs(skill.frontmatter.globs);

  return {
    id: skill.id,
    name: skill.frontmatter.name,
    description: skill.frontmatter.description ?? "",
    globs,
    alwaysApply: Boolean(skill.frontmatter.alwaysApply)
  };
}

function normalizeGlobs(globs: SkillFrontmatter["globs"]): string[] {
  if (!globs) {
    return [];
  }

  if (Array.isArray(globs)) {
    return globs.map((glob) => String(glob)).filter(Boolean);
  }

  return [String(globs)];
}
